
export interface Flight {
  flightId: string;
  airline: string;
  price: number;
  currency: string;
  from: string;
  to: string;
  departureTime: string;
  arrivalTime: string;
  flightDuration: string;
  stops: number;
  flightClass: string;
  seatAvailability: number;
  baggageAllowance: string;
  aircraftType: string;
  flightStatus: string;
  gate: string;
}

export const flights: Flight[] = [
  {
    flightId: "FL123",
    airline: "Air India",
    price: 600,
    currency: "USD",
    from: "New York (JFK)",
    to: "London (LHR)",
    departureTime: "2024-12-20T16:30:00",
    arrivalTime: "2024-12-20T17:45:00",
    flightDuration: "7h 15m",
    stops: 0,
    flightClass: "Economy",
    seatAvailability: 180,
    baggageAllowance: "23 kg",
    aircraftType: "Boeing 777",
    flightStatus: "On Time",
    gate: "B1",
  },
  {
    flightId: "FL124",
    airline: "British Airways",
    price: 750,
    currency: "USD",
    from: "London (LHR)",
    to: "Tokyo (HND)",
    departureTime: "2024-12-21T12:00:00",
    arrivalTime: "2024-12-21T23:50:00",
    flightDuration: "11h 50m",
    stops: 0,
    flightClass: "Economy",
    seatAvailability: 150,
    baggageAllowance: "30 kg",
    aircraftType: "Airbus A380",
    flightStatus: "On Time",
    gate: "C3",
  },
  {
    flightId: "FL125",
    airline: "Delta Airlines",
    price: 800,
    currency: "USD",
    from: "Los Angeles (LAX)",
    to: "Paris (CDG)",
    departureTime: "2024-12-22T10:30:00",
    arrivalTime: "2024-12-22T15:00:00",
    flightDuration: "10h 30m",
    stops: 0,
    flightClass: "Economy",
    seatAvailability: 140,
    baggageAllowance: "23 kg",
    aircraftType: "Boeing 787",
    flightStatus: "On Time",
    gate: "D5",
  },
  {
    flightId: "FL126",
    airline: "Singapore Airlines",
    price: 850,
    currency: "USD",
    from: "Singapore (SIN)",
    to: "Sydney (SYD)",
    departureTime: "2024-12-23T21:00:00",
    arrivalTime: "2024-12-24T07:30:00",
    flightDuration: "7h 30m",
    stops: 0,
    flightClass: "Business",
    seatAvailability: 100,
    baggageAllowance: "40 kg",
    aircraftType: "Airbus A350",
    flightStatus: "On Time",
    gate: "B2",
  },
  {
    flightId: "FL127",
    airline: "Qatar Airways",
    price: 900,
    currency: "USD",
    from: "Doha (DOH)",
    to: "New York (JFK)",
    departureTime: "2024-12-20T19:00:00",
    arrivalTime: "2024-12-20T23:30:00",
    flightDuration: "14h 30m",
    stops: 0,
    flightClass: "Economy",
    seatAvailability: 160,
    baggageAllowance: "30 kg",
    aircraftType: "Boeing 777",
    flightStatus: "On Time",
    gate: "A1",
  },
  {
    flightId: "FL128",
    airline: "Emirates",
    price: 950,
    currency: "USD",
    from: "Dubai (DXB)",
    to: "Sydney (SYD)",
    departureTime: "2024-12-21T14:15:00",
    arrivalTime: "2024-12-21T15:30:00",
    flightDuration: "14h 15m",
    stops: 0,
    flightClass: "Business",
    seatAvailability: 80,
    baggageAllowance: "35 kg",
    aircraftType: "Airbus A380",
    flightStatus: "On Time",
    gate: "D4",
  },
  {
    flightId: "FL129",
    airline: "Cathay Pacific",
    price: 600,
    currency: "USD",
    from: "Hong Kong (HKG)",
    to: "Los Angeles (LAX)",
    departureTime: "2024-12-22T13:00:00",
    arrivalTime: "2024-12-22T11:30:00",
    flightDuration: "13h 30m",
    stops: 0,
    flightClass: "Economy",
    seatAvailability: 120,
    baggageAllowance: "30 kg",
    aircraftType: "Boeing 777",
    flightStatus: "On Time",
    gate: "C6",
  },
  {
    flightId: "FL130",
    airline: "Air France",
    price: 700,
    currency: "USD",
    from: "Paris (CDG)",
    to: "New York (JFK)",
    departureTime: "2024-12-23T18:45:00",
    arrivalTime: "2024-12-23T20:00:00",
    flightDuration: "8h 15m",
    stops: 0,
    flightClass: "Economy",
    seatAvailability: 130,
    baggageAllowance: "23 kg",
    aircraftType: "Airbus A330",
    flightStatus: "On Time",
    gate: "B7",
  },
  {
    flightId: "FL131",
    airline: "American Airlines",
    price: 700,
    currency: "USD",
    from: "Chicago (ORD)",
    to: "London (LHR)",
    departureTime: "2024-12-22T09:30:00",
    arrivalTime: "2024-12-22T22:00:00",
    flightDuration: "9h 30m",
    stops: 0,
    flightClass: "Economy",
    seatAvailability: 110,
    baggageAllowance: "23 kg",
    aircraftType: "Boeing 787",
    flightStatus: "Delayed",
    gate: "A2",
  },
  {
    flightId: "FL132",
    airline: "Japan Airlines",
    price: 950,
    currency: "USD",
    from: "Tokyo (HND)",
    to: "Los Angeles (LAX)",
    departureTime: "2024-12-22T14:30:00",
    arrivalTime: "2024-12-22T11:30:00",
    flightDuration: "9h 0m",
    stops: 0,
    flightClass: "Business",
    seatAvailability: 50,
    baggageAllowance: "40 kg",
    aircraftType: "Boeing 787",
    flightStatus: "On Time",
    gate: "C5",
  }
];

export interface Hotel {
  hotelId: string;
  name: string;
  location: string;
  pricePerNight: number;
  rating: number; 
  amenities: string[]; 
  availableRooms: number; 
  checkInTime: string; 
  checkOutTime: string; 
  imageUrl: string;
}

export const hotels: Hotel[] = [
  {
    hotelId: "1",
    name: "The Grand Palace",
    location: "New York, USA",
    pricePerNight: 1500,
    rating: 5,
    amenities: ["Free WiFi", "Pool", "Gym", "Spa", "Bar", "Restaurant"],
    availableRooms: 10,
    checkInTime: "2:00 PM",
    checkOutTime: "11:00 AM",
    imageUrl: "/1.jpg",
  },
  {
    hotelId: "2",
    name: "Ocean View Resort",
    location: "Maldives",
    pricePerNight: 3000,
    rating: 4.5,
    amenities: ["Free WiFi", "Beach Access", "Infinity Pool", "Restaurant", "Bar"],
    availableRooms: 5,
    checkInTime: "3:00 PM",
    checkOutTime: "12:00 PM",
    imageUrl: "/2.jpg.crdownload",
  },
  {
    hotelId: "3",
    name: "Mountain Retreat",
    location: "Switzerland",
    pricePerNight: 2000,
    rating: 4.8,
    amenities: ["Free WiFi", "Ski Pass", "Restaurant", "Sauna", "Gym"],
    availableRooms: 8,
    checkInTime: "4:00 PM",
    checkOutTime: "10:00 AM",
    imageUrl: "/3.jpg",
  },
  {
    hotelId: "4",
    name: "City Center Inn",
    location: "London, UK",
    pricePerNight: 1200,
    rating: 4.2,
    amenities: ["Free WiFi", "Restaurant", "Bar", "24-hour Concierge"],
    availableRooms: 20,
    checkInTime: "2:00 PM",
    checkOutTime: "11:00 AM",
    imageUrl: "/4.jpg",
  },
  {
    hotelId: "5",
    name: "Sunset Villa",
    location: "Bali, Indonesia",
    pricePerNight: 1800,
    rating: 4.7,
    amenities: ["Private Pool", "Spa", "Bar", "Restaurant", "Yoga Classes"],
    availableRooms: 4,
    checkInTime: "3:00 PM",
    checkOutTime: "12:00 PM",
    imageUrl: "/5.jpg",
  },
  {
    hotelId: "6",
    name: "Desert Oasis Resort",
    location: "Dubai, UAE",
    pricePerNight: 2500,
    rating: 4.9,
    amenities: ["Luxury Spa", "Private Beach", "Infinity Pool", "Golf Course", "Restaurant"],
    availableRooms: 6,
    checkInTime: "4:00 PM",
    checkOutTime: "1:00 PM",
    imageUrl: "/6.jpg",
  },
  {
    hotelId: "7",
    name: "Cozy Cabin Lodge",
    location: "Aspen, USA",
    pricePerNight: 1600,
    rating: 4.4,
    amenities: ["Free WiFi", "Hot Tub", "Restaurant", "Ski Pass", "Bar"],
    availableRooms: 12,
    checkInTime: "2:00 PM",
    checkOutTime: "11:00 AM",
    imageUrl: "/7.jpg",
  },
  {
    hotelId: "8",
    name: "Luxury Heights Hotel",
    location: "Paris, France",
    pricePerNight: 2800,
    rating: 4.8,
    amenities: ["Free WiFi", "24-hour Concierge", "Spa", "Restaurant", "Bar"],
    availableRooms: 8,
    checkInTime: "2:00 PM",
    checkOutTime: "12:00 PM",
    imageUrl: "/8.jpg",
  },
  {
    hotelId: "9",
    name: "Tropical Paradise Resort",
    location: "Hawaii, USA",
    pricePerNight: 2200,
    rating: 4.6,
    amenities: ["Beach Access", "Free WiFi", "Infinity Pool", "Restaurant", "Bar"],
    availableRooms: 15,
    checkInTime: "3:00 PM",
    checkOutTime: "11:00 AM",
    imageUrl: "/9.jpg",
  },
  {
    hotelId: "10",
    name: "Cultural Heritage Inn",
    location: "Rome, Italy",
    pricePerNight: 1300,
    rating: 4.3,
    amenities: ["Free WiFi", "Restaurant", "Bar", "Cultural Tours"],
    availableRooms: 18,
    checkInTime: "3:00 PM",
    checkOutTime: "12:00 PM",
    imageUrl: "/10.jpg",
  },
  {
    hotelId: "11",
    name: "Skyline Towers",
    location: "Tokyo, Japan",
    pricePerNight: 2900,
    rating: 5,
    amenities: ["Sky Lounge", "Free WiFi", "Restaurant", "Gym", "Spa"],
    availableRooms: 10,
    checkInTime: "3:00 PM",
    checkOutTime: "11:00 AM",
    imageUrl: "/11.jpg",
  },
  {
    hotelId: "12",
    name: "Forest Edge Retreat",
    location: "Canada",
    pricePerNight: 1700,
    rating: 4.4,
    amenities: ["Hiking Trails", "Free WiFi", "Hot Tub", "Sauna", "Bar"],
    availableRooms: 7,
    checkInTime: "2:00 PM",
    checkOutTime: "11:00 AM",
    imageUrl: "/12.jpg",
  },
  {
    hotelId: "13",
    name: "Ocean Breeze Hotel",
    location: "Cancun, Mexico",
    pricePerNight: 2000,
    rating: 4.7,
    amenities: ["Beach Access", "Free WiFi", "Restaurant", "Pool", "Bar"],
    availableRooms: 20,
    checkInTime: "2:00 PM",
    checkOutTime: "12:00 PM",
    imageUrl: "/13.jpg",
  },
  {
    hotelId: "14",
    name: "Vibrant Villas",
    location: "Thailand",
    pricePerNight: 1400,
    rating: 4.2,
    amenities: ["Free WiFi", "Private Pool", "Restaurant", "Bar"],
    availableRooms: 5,
    checkInTime: "3:00 PM",
    checkOutTime: "11:00 AM",
    imageUrl: "/14.jpg",
  },
  {
    hotelId: "15",
    name: "Mountain View Resort",
    location: "Switzerland",
    pricePerNight: 2200,
    rating: 4.8,
    amenities: ["Free WiFi", "Ski Pass", "Gym", "Spa", "Restaurant"],
    availableRooms: 10,
    checkInTime: "3:00 PM",
    checkOutTime: "12:00 PM",
    imageUrl: "/15.jpg",
  },
  {
    hotelId: "16",
    name: "Seaside Paradise",
    location: "Malta",
    pricePerNight: 1600,
    rating: 4.6,
    amenities: ["Beach Access", "Free WiFi", "Restaurant", "Bar", "Pool"],
    availableRooms: 12,
    checkInTime: "2:00 PM",
    checkOutTime: "11:00 AM",
    imageUrl: "/16.jpg",
  },
  {
    hotelId: "17",
    name: "Royal Palace Inn",
    location: "Los Angeles, USA",
    pricePerNight: 2500,
    rating: 4.9,
    amenities: ["Spa", "Gym", "Restaurant", "Free WiFi", "Bar"],
    availableRooms: 6,
    checkInTime: "3:00 PM",
    checkOutTime: "12:00 PM",
    imageUrl: "/17.jpg",
  },
  {
    hotelId: "18",
    name: "Golden Sands Resort",
    location: "Dubai, UAE",
    pricePerNight: 2700,
    rating: 4.8,
    amenities: ["Beach Access", "Free WiFi", "Gym", "Infinity Pool", "Restaurant"],
    availableRooms: 10,
    checkInTime: "2:00 PM",
    checkOutTime: "12:00 PM",
    imageUrl: "/18.jpg",
  },
  {
    hotelId: "19",
    name: "Peaceful Retreat",
    location: "Thailand",
    pricePerNight: 1500,
    rating: 4.3,
    amenities: ["Free WiFi", "Sauna", "Restaurant", "Yoga Classes", "Bar"],
    availableRooms: 15,
    checkInTime: "3:00 PM",
    checkOutTime: "12:00 PM",
    imageUrl: "/13.jpg",
  },
  {
    hotelId: "20",
    name: "Crystal Bay Resort",
    location: "Bora Bora",
    pricePerNight: 3200,
    rating: 5,
    amenities: ["Private Beach", "Free WiFi", "Restaurant", "Bar", "Spa", "Gym"],
    availableRooms: 4,
    checkInTime: "3:00 PM",
    checkOutTime: "11:00 AM",
    imageUrl: "/20.jpg",
  },
];

export interface Activity {
  activityId: string; 
  name: string;       
  location: string;   
  price: number;     
  rating: number;    
  description: string; 
  img:string;
}

export const activities: Activity[] = [
  {
    activityId: "1",
    name: "Scuba Diving",
    location: "Maldives",
    price: 5000,
    rating: 4.8,
    img: "/20.jpg",
    description: "Experience underwater life in the crystal clear waters of the Maldives.",
  },
  {
    activityId: "2",
    name: "Safari Adventure",
    location: "Kenya",
    price: 8000,
    rating: 4.9,
    img: "/11.jpg",
    description: "Explore the wild and witness exotic animals in their natural habitat.",
  },
  {
    activityId: "3",
    name: "Skydiving",
    location: "Dubai",
    img: "/18.jpg",
    price: 10000,
    rating: 5.0,
    description: "Feel the adrenaline rush while skydiving over Dubai's iconic skyline.",
  },
  {
    activityId: "4",
    name: "Hot Air Balloon Ride",
    location: "Cappadocia, Turkey",
    price: 6000,
    img: "./17.jpg",
    rating: 4.7,
    description: "Soar above the surreal landscapes of Cappadocia in a hot air balloon.",
  },
  {
    activityId: "5",
    name: "Northern Lights Tour",
    location: "Reykjavik, Iceland",
    price: 7000,
    img: "./16.jpg",
    rating: 4.9,
    description: "Witness the magical Northern Lights from the best viewpoints in Iceland.",
  },
  {
    activityId: "6",
    name: "Wine Tasting",
    location: "Tuscany, Italy",
    price: 4000,
    img: "./15.jpg",
    rating: 4.5,
    description: "Savor the finest wines in the scenic vineyards of Tuscany.",
  },
  {
    activityId: "7",
    name: "White Water Rafting",
    location: "Rishikesh, India",
    price: 3500,
    rating: 4.6,
    img: "./14.jpg",
    description: "Experience the thrill of rafting on the rapids of the Ganges River.",
  },
  {
    activityId: "8",
    name: "Zip Lining",
    location: "Costa Rica",
    price: 4500,
    rating: 4.8,
    img: "./13.jpg",
    description: "Fly through the lush rainforests of Costa Rica on a thrilling zip line adventure.",
  },
  {
    activityId: "9",
    name: "Desert Safari",
    location: "Rajasthan, India",
    price: 3000,
    img: "./12.jpg",
    rating: 4.7,
    description: "Enjoy a camel ride and a traditional Rajasthani meal under the stars.",
  },
  {
    activityId: "10",
    name: "Snorkeling",
    location: "Great Barrier Reef, Australia",
    price: 5500,
    img: "./11.jpg",
    rating: 4.8,
    description: "Discover the vibrant marine life of the world's largest coral reef system.",
  },
  {
    activityId: "11",
    name: "Helicopter Tour",
    location: "New York City, USA",
    price: 12000,
    img: "./10.jpg",
    rating: 4.9,
    description: "Get a bird's-eye view of NYC's iconic landmarks from a helicopter.",
  },
  {
    activityId: "12",
    name: "Cultural Tour",
    location: "Kyoto, Japan",
    price: 5000,
    img: "./9.jpg",
    rating: 4.6,
    description: "Explore ancient temples, traditional tea houses, and stunning gardens.",
  },
  {
    activityId: "13",
    name: "Mountain Trekking",
    location: "Himalayas, Nepal",
    price: 15000,
    img: "./8.jpg",
    rating: 5.0,
    description: "Embark on an unforgettable trek through the majestic Himalayan range.",
  },
  {
    activityId: "14",
    name: "Cooking Class",
    location: "Bangkok, Thailand",
    price: 2500,
    rating: 4.5,
    img: "./7.jpg",
    description: "Learn to cook authentic Thai dishes with expert local chefs.",
  },
  {
    activityId: "15",
    name: "Surfing Lessons",
    location: "Bali, Indonesia",
    img: "./3.jpg",
    price: 4000,
    rating: 4.7,
    description: "Catch some waves with professional surfing instructors in Bali.",
  },
];
